CharacterScreenInventoryListModule.prototype.removeItemFromSlot = EIMO.Generic.removeItemFromSlot(CharacterScreenInventoryListModule.prototype.removeItemFromSlot);
CharacterScreenInventoryListModule.prototype.assignItemToSlot = EIMO.Generic.assignItemToSlot(CharacterScreenInventoryListModule.prototype.assignItemToSlot);
CharacterScreenInventoryListModule.prototype.createItemSlots = EIMO.Generic.createItemSlots(CharacterScreenInventoryListModule.prototype.createItemSlots);
